# Generated by Django 3.2 on 2021-04-29 13:28

from django.db import migrations, models
import django.db.models.deletion
import listings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='day',
            field=models.DateField(blank=True, null=True, validators=[listings.validators.validate_day]),
        ),
        migrations.CreateModel(
            name='BlockedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(validators=[listings.validators.validate_day])),
                ('hotel_room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_days', to='listings.hotelroomtype')),
            ],
        ),
    ]
